### ISSUE TITLE
publish does not seem to purge

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-admin#69]
Follow up issue https://github.com/adobe/helix-content-bus/issues/76.

Make a change in a page and `/preview` the change.
POST to `/publish` to get the page in `/live`
Check in the S3 buket, the changes are here. All good.

Open the corresponding `url_with_.hlx.page` url: this still shows the old version.
Run `curl -X PURGE url_with_.hlx.page` and reopen the `url_with_.hlx.page` page: it is now up-to-date.
The purge executed in the publish action does not seem to do his job.

**Comment by tripodsan** [comment]
@kptdobe did you check the logs ?

**Comment by kptdobe** [comment]
Where are the logs that I am supposed to check ?
I double-checked and I confirm that the purge does not work neither for the content nor for the code. I always have to run the  `curl -X PURGE...` to get my changes on the `.live` domain.

**Comment by kptdobe** [comment]
In CloudWatch, I found an entry: 

```
[INFO] sending PURGE request to https://superdevoluy--kptdobe.hlx.live/ | [INFO] sending PURGE request to https://superdevoluy--kptdobe.hlx.live/
```

The branch is missing...

**Comment by kptdobe** [comment]
And I would expect to find a purge to: https://main--superdevoluy--kptdobe.hlx.live/blocks/carousel/carousel.js which is one of the file I changed in the commit.

**Comment by tripodsan** [comment]
> In CloudWatch, I found an entry:
> 
> ```
> [INFO] sending PURGE request to https://superdevoluy--kptdobe.hlx.live/ | [INFO] sending PURGE request to https://superdevoluy--kptdobe.hlx.live/
> ```
> 
> The branch is missing...

yes. because the live domains didn't have a `branch--`. we probably need to hard-code the exceptions (or always purge both)

**Comment by tripodsan** [comment]
> And I would expect to find a purge to: https://main--superdevoluy--kptdobe.hlx.live/blocks/carousel/carousel.js which is one of the file I changed in the commit. Or do we flush the full domain ?

purging the code-bus is not supported yet :-)
see https://github.com/adobe/helix-code-bus/issues/52

**Comment by rofe** [comment]
> yes. because the live domains didn't have a branch--. we probably need to hard-code the exceptions (or always purge both)

Accoridng to @davidnuescheler all hlx3 outer CDNs should eventually have a branch prefix. So purging both until we've had the time to clean up the couple exceptions is probably the best solution for now.
